import strawberry


@strawberry.type
class Book:
    id: strawberry.ID
    title: str
    author: str


books = [
    Book(id="book1", title="The Great Gatsby", author="F. Scott Fitzgerald"),
    Book(id="book2", title="To Kill a Mockingbird", author="Harper Lee"),
    Book(id="book3", title="The Hunger Games", author="Suzanne Collins"),
    Book(id="book4", title="The Da Vinci Code", author="Dan Brown"),
    Book(id="book5", title="1984", author="George Orwell"),
    Book(id="book6", title="Pride and Prejudice", author="Jane Austen"),
    Book(id="book7", title="Lord of the Flies", author="William Golding"),
    Book(id="book8", title="The Catcher in the Rye", author="J.D. Salinger"),
    Book(id="book9", title="Harry Potter and the Sorcerer's Stone", author="J.K. Rowling"),
    Book(id="book10", title="The Hobbit", author="J.R.R. Tolkien"),
    Book(id="book11", title="Brave New World", author="Aldous Huxley"),
    Book(id="book12", title="Animal Farm", author="George Orwell"),
    Book(id="book13", title="The Chronicles of Narnia", author="C.S. Lewis"),
    Book(id="book14", title="Jane Eyre", author="Charlotte Brontë"),
    Book(id="book15", title="Wuthering Heights", author="Emily Brontë"),
    Book(id="book16", title="Great Expectations", author="Charles Dickens"),
    Book(id="book17", title="A Tale of Two Cities", author="Charles Dickens"),
    Book(id="book18", title="The Picture of Dorian Gray", author="Oscar Wilde"),
    Book(id="book19", title="Moby-Dick", author="Herman Melville"),
    Book(id="book20", title="The Odyssey", author="Homer"),
    Book(id="book21", title="The Iliad", author="Homer"),
    Book(id="book22", title="War and Peace", author="Leo Tolstoy"),
    Book(id="book23", title="Anna Karenina", author="Leo Tolstoy"),
    Book(id="book24", title="Crime and Punishment", author="Fyodor Dostoevsky"),
    Book(id="book25", title="The Brothers Karamazov", author="Fyodor Dostoevsky"),
    Book(id="book26", title="One Hundred Years of Solitude", author="Gabriel García Márquez"),
    Book(id="book27", title="Love in the Time of Cholera", author="Gabriel García Márquez"),
    Book(id="book28", title="The Alchemist", author="Paulo Coelho"),
    Book(id="book29", title="The Little Prince", author="Antoine de Saint-Exupéry"),
    Book(id="book30", title="Don Quixote", author="Miguel de Cervantes"),
    Book(id="book31", title="Ulysses", author="James Joyce"),
    Book(id="book32", title="The Sound and the Fury", author="William Faulkner"),
    Book(id="book33", title="As I Lay Dying", author="William Faulkner"),
    Book(id="book34", title="The Grapes of Wrath", author="John Steinbeck"),
    Book(id="book35", title="Of Mice and Men", author="John Steinbeck"),
    Book(id="book36", title="Catch-22", author="Joseph Heller"),
    Book(id="book37", title="Slaughterhouse-Five", author="Kurt Vonnegut"),
    Book(id="book38", title="The Bell Jar", author="Sylvia Plath"),
    Book(id="book39", title="The Handmaid's Tale", author="Margaret Atwood"),
    Book(id="book40", title="Fahrenheit 451", author="Ray Bradbury"),
    Book(id="book41", title="The Martian Chronicles", author="Ray Bradbury"),
    Book(id="book42", title="Dune", author="Frank Herbert"),
    Book(id="book43", title="Foundation", author="Isaac Asimov"),
    Book(id="book44", title="Ender's Game", author="Orson Scott Card"),
    Book(id="book45", title="The Hitchhiker's Guide to the Galaxy", author="Douglas Adams"),
    Book(id="book46", title="Neuromancer", author="William Gibson"),
    Book(id="book47", title="Snow Crash", author="Neal Stephenson"),
    Book(id="book48", title="The Road", author="Cormac McCarthy"),
    Book(id="book49", title="No Country for Old Men", author="Cormac McCarthy"),
    Book(id="book50", title="Blood Meridian", author="Cormac McCarthy"),
    Book(id="book51", title="Beloved", author="Toni Morrison"),
    Book(id="book52", title="Song of Solomon", author="Toni Morrison"),
    Book(id="book53", title="The Color Purple", author="Alice Walker"),
    Book(id="book54", title="Invisible Man", author="Ralph Ellison"),
    Book(id="book55", title="Native Son", author="Richard Wright"),
    Book(id="book56", title="Their Eyes Were Watching God", author="Zora Neale Hurston"),
    Book(id="book57", title="The Sun Also Rises", author="Ernest Hemingway"),
    Book(id="book58", title="For Whom the Bell Tolls", author="Ernest Hemingway"),
    Book(id="book59", title="The Old Man and the Sea", author="Ernest Hemingway"),
    Book(id="book60", title="A Farewell to Arms", author="Ernest Hemingway"),
    Book(id="book61", title="The Lord of the Rings", author="J.R.R. Tolkien"),
    Book(id="book62", title="The Silmarillion", author="J.R.R. Tolkien"),
    Book(id="book63", title="Harry Potter and the Chamber of Secrets", author="J.K. Rowling"),
    Book(id="book64", title="Harry Potter and the Prisoner of Azkaban", author="J.K. Rowling"),
    Book(id="book65", title="Harry Potter and the Goblet of Fire", author="J.K. Rowling"),
    Book(id="book66", title="The Shining", author="Stephen King"),
    Book(id="book67", title="It", author="Stephen King"),
    Book(id="book68", title="The Stand", author="Stephen King"),
    Book(id="book69", title="Carrie", author="Stephen King"),
    Book(id="book70", title="Pet Sematary", author="Stephen King"),
    Book(id="book71", title="Misery", author="Stephen King"),
    Book(id="book72", title="Dracula", author="Bram Stoker"),
    Book(id="book73", title="Frankenstein", author="Mary Shelley"),
    Book(id="book74", title="The Strange Case of Dr Jekyll and Mr Hyde", author="Robert Louis Stevenson"),
    Book(id="book75", title="Treasure Island", author="Robert Louis Stevenson"),
    Book(id="book76", title="Robinson Crusoe", author="Daniel Defoe"),
    Book(id="book77", title="Gulliver's Travels", author="Jonathan Swift"),
    Book(id="book78", title="Alice's Adventures in Wonderland", author="Lewis Carroll"),
    Book(id="book79", title="Through the Looking-Glass", author="Lewis Carroll"),
    Book(id="book80", title="The Adventures of Tom Sawyer", author="Mark Twain"),
    Book(id="book81", title="Adventures of Huckleberry Finn", author="Mark Twain"),
    Book(id="book82", title="A Connecticut Yankee in King Arthur's Court", author="Mark Twain"),
    Book(id="book83", title="The Prince and the Pauper", author="Mark Twain"),
    Book(id="book84", title="Little Women", author="Louisa May Alcott"),
    Book(id="book85", title="Anne of Green Gables", author="L.M. Montgomery"),
    Book(id="book86", title="The Secret Garden", author="Frances Hodgson Burnett"),
    Book(id="book87", title="Black Beauty", author="Anna Sewell"),
    Book(id="book88", title="The Wind in the Willows", author="Kenneth Grahame"),
    Book(id="book89", title="Peter Pan", author="J.M. Barrie"),
    Book(id="book90", title="The Jungle Book", author="Rudyard Kipling"),
    Book(id="book91", title="The Call of the Wild", author="Jack London"),
    Book(id="book92", title="White Fang", author="Jack London"),
    Book(id="book93", title="The Sea-Wolf", author="Jack London"),
    Book(id="book94", title="Heart of Darkness", author="Joseph Conrad"),
    Book(id="book95", title="Lord Jim", author="Joseph Conrad"),
    Book(id="book96", title="The Stranger", author="Albert Camus"),
    Book(id="book97", title="The Plague", author="Albert Camus"),
    Book(id="book98", title="The Trial", author="Franz Kafka"),
    Book(id="book99", title="The Metamorphosis", author="Franz Kafka"),
]
